import Head from 'next/head'
import { useState } from 'react';
import LessonStart from '/components/Lesson/LessonStart'
import LessonMain from '/components/Lesson/LessonMain'
import LessonEnd from '/components/Lesson/LessonEnd'


const Lesson = () => {
    const [countdownFinished, setCountdownFinished] = useState(false);
    const [lessonFinished, setLessonFinished] = useState(false);

    return(
        <>
            <Head>
                <title>Lesson</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!countdownFinished && <LessonStart  setCountdownFinished={setCountdownFinished} />}
            {lessonFinished === false && <LessonMain {...{countdownFinished}} {...{setLessonFinished}}/>}
            {lessonFinished && <LessonEnd />}
        </>
    )
}

export default Lesson