import Head from 'next/head'
import { useState } from 'react';
import LessonStart from '/components/Lesson/LessonStart'
import LessonMain from '/components/Lesson/LessonMain'


const Lesson = () => {
    const [finished, setFinished] = useState(false);

    return(
        <>
            <Head>
                <title>Lesson</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!finished && <LessonStart  setFinished={setFinished} />}
            <LessonMain {...{finished}}/>
        </>
    )
}

export default Lesson