import Head from 'next/head'
import LessonStart from '/components/Lesson/LessonStart'
import { useState } from 'react';


const Lesson = () => {
    const [finished, setFinished] = useState(false);
    console.log(finished);

    return(
        <>
            <Head>
                <title>Lesson</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!finished && <LessonStart {...finished} setFinished={setFinished}/>}
        </>
    )
}

export default Lesson